#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import launchpadtools
import shutil
import tempfile


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
            description='Update patches builds to launchpad.'
            )
    parser.add_argument(
            '--update-patches', '-u',
            default=False,
            action='store_true',
            help='update patches (default: false)'
            )
    parser.add_argument(
            '--orig', '-r',
            type=str,
            required=True,
            help='orig source'
            )
    parser.add_argument(
            '--debian', '-d',
            type=str,
            help='debian source'
            )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    # create tempory directory
    tmp_dir = tempfile.mkdtemp()

    launchpadtools.create_repo(
            args.orig,
            args.debian,
            tmp_dir,
            args.update_patches
            )
    launchpadtools.submit(
        tmp_dir,
        args.ubuntu_releases,
        args.resubmission,
        args.slot,
        args.ppa,
        args.debfullname,
        args.debemail,
        args.debuild_params,
        args.version_override,
        args.version_append_hash,
        args.force
        )

    shutil.rmtree(tmp_dir)
