#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import launchpadtools


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Clone any repository or directory into a cache.'
        )
    parser.add_argument(
        'source',
        metavar='SOURCE',
        type=str,
        help='source repository/directory'
        )
    parser.add_argument(
        '-v', '--version',
        action='version',
        version='launchpadtools %s' % launchpadtools.__about__.__version__
        )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    launchpadtools.cclone.cclone(
        args.source,
        subdirectory=args.subdirectory
        )
