#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import launchpadtools


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
            description='Clone any repository or directory.'
            )
    parser.add_argument(
            '--source', '-s',
            type=str,
            required=True,
            help='source repository/directory'
            )
    parser.add_argument(
            '--out', '-o',
            type=str,
            required=True,
            help='output directory'
            )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    launchpadtools.clone.clone(args.source, args.out)
