#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import launchpadtools


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
            description='Update patches builds to launchpad.'
            )
    parser.add_argument(
            '--update-patches', '-u',
            default=False,
            action='store_true',
            help='update patches (default: false)'
            )
    parser.add_argument(
            '--orig', '-r',
            type=str,
            required=True,
            help='orig source'
            )
    parser.add_argument(
            '--debian', '-d',
            type=str,
            help='debian source'
            )
    parser.add_argument(
            '--out', '-o',
            type=str,
            required=True,
            help='output directory'
            )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    launchpadtools.create_repo(
            args.orig,
            args.debian,
            args.out,
            args.update_patches
            )
