#!/usr/bin/env python
#
import argparse
import re


def _sanitize_version_string(string):
    out = string
    out = re.sub('[-_~+]?alpha', '~alpha', out)
    out = re.sub('[-_~+]?ALPHA', '~alpha', out)
    out = re.sub('[-_~+]?beta', '~beta', out)
    out = re.sub('[-_~+]?BETA', '~beta', out)
    out = re.sub('[-_~+]?rc', '~rc', out)
    out = re.sub('[-_~+]?RC', '~rc', out)
    return out


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Sanitize version string for Debian.'
        )
    parser.add_argument(
        'string',
        help='Input version string.'
        )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    print(_sanitize_version_string(args.string))
